apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: staging-

resources:
- ../../base

components:
- ../../components/non-prod

patches:
  - path: configMap.yaml

patchesStrategicMerge:
- version.yaml
#- settings.yaml