apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-app
  template:
    metadata:
      labels:
        app: reports-app
    spec:
      containers:
        - name: reports
          image: nicholasjackson/fake-service:latest
          imagePullPolicy: Always
          env:
          - name: NAME
            value: Reports Service
          - name: MESSAGE
            value: Hello from reports service
          ports:
          - containerPort: 9090
          resources:
            limits:
              cpu: 500
              memory: 8Mi
            requests:
              cpu: 500
              memory: 4Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 45
            periodSeconds: 3