apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  template:
    spec:
      containers:
      - name: ingestion
        env:
        - name: MESSAGE
          value: Hello from ingestion service in production
        - name: LOG_LEVEL
          value: debug