apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-

resources:
- ../../../base/reports

#components:
#  - ../../variants/non-prod

patchesStrategicMerge:
- version.yaml
- settings.yaml