apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-app
  template:
    metadata:
      labels:
        app: ingestion-app
    spec:
      containers:
        - name: ingestion
          image: nicholasjackson/fake-service:latest
          imagePullPolicy: Always
          env:
          - name: NAME
            value: Ingestion Service
          - name: MESSAGE
            value: Hello from ingestion service
          ports:
          - containerPort: 9090
          resources:
            limits:
              cpu: 500m
              memory: 8Mi
            requests:
              cpu: 500m
              memory: 4Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 45
            periodSeconds: 3