apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-deployment
spec:
  template:
    spec:
      containers:
      - name: reports
        env:
        - name: LOG_LEVEL
          value: debug